### ISSUE TITLE
Jython interpreter does not work

### ISSUE THREAD

**Issue by hadim** [hadim/scijava-jupyter-kernel#9]
Simple code like `2+2` works but more complex statement such as `print()` produces an error : 

```
print("test")
```

```
SyntaxError: ("no viable alternative at input 'print'", ('<string>', 1, 0, 'print("test")\n'))
```

I was able to isolate the error : 

```java
package org.scijava.jupyterkernel;

import javax.script.ScriptEngine;
import javax.script.ScriptException;
import org.scijava.Context;
import org.scijava.script.ScriptLanguage;
import org.scijava.script.ScriptService;

/**
 *
 * @author Hadrien Mary
 */
public class TestScriptEngine {

    public static void main(String[] args) throws ScriptException {
        // Only for testing purpose

        Context context = new Context();
        ScriptService scriptService = context.getService(ScriptService.class);
        ScriptLanguage scriptLanguage = scriptService.getLanguageByName("python");
        ScriptEngine engine = scriptLanguage.getScriptEngine();

        engine.eval("print('Hello'");

        context.dispose();
    }

}
```

The error is 

```
exec-maven-plugin:1.2.1:exec (default-cli) @ scijava-jupyter-kernel ---
Exception in thread "main" javax.script.ScriptException: SyntaxError: ("no viable alternative at input 'print'", ('<string>', 1, 0, "print('Hello'\n"))

	at org.scijava.plugins.scripting.jython.JythonScriptEngine.eval(JythonScriptEngine.java:66)
	at org.scijava.jupyterkernel.TestScriptEngine.main(TestScriptEngine.java:28)
Caused by: SyntaxError: ("no viable alternative at input 'print'", ('<string>', 1, 0, "print('Hello'\n"))

	at org.python.core.ParserFacade.fixParseError(ParserFacade.java:95)
	at org.python.core.ParserFacade.parse(ParserFacade.java:205)
	at org.python.core.CompileFunction.compile(__builtin__.java:1672)
	at org.python.core.CompileFunction.compile(__builtin__.java:1648)
	at org.python.core.CompileFunction.compile(__builtin__.java:1640)
	at org.python.core.__builtin__.eval(__builtin__.java:492)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:251)
	at org.scijava.plugins.scripting.jython.JythonScriptEngine.eval(JythonScriptEngine.java:63)
	... 1 more

```

**Comment by hadim** [comment]
Maybe switching to Jython 2.7 will help ? (or not...)

See https://github.com/scijava/scripting-jython/issues/3

**Comment by hadim** [comment]
Same error with Jython 2.7.0 ... :-(

**Comment by hadim** [comment]
It appears that when using `ScriptService` Jython code is correctly executed but not when I use directly `ScriptEngine`

**Comment by hadim** [comment]
I need help here.

@ctrueden when you'll have time to have a look at the project please spend sometime on this.

**Comment by ctrueden** [comment]
@hadim I will try to take a look either today or early next week. I agree that support for Jython via this mechanism is very important.

**Comment by ctrueden** [comment]
I think this is a general issue with the `scripting-jython` plugin. I see that same error when attempting to use Jython in the Script Interpreter (shift+`]` within Fiji). Hopefully, fixing it there will also fix it from Jupyter.

**Comment by hadim** [comment]
Thank you.

I think Jython and Groovy should be supported out of the box. And others languages depending on the user demand.

**Comment by ctrueden** [comment]
I took a very quick look. I notice that [you use the `eval` method of `ScriptEngine`](https://github.com/hadim/scijava-jupyter-kernel/blob/4bab7eac84373fcf093d3629ae9bad231755d4e2/src/main/java/org/scijava/jupyterkernel/console/InteractiveConsole.java#L148), which is the same thing the ScriptInterpreter uses, and clearly what is broken here in Python. Have you considered simply executing the script using the `ScriptService` instead, similar to how the Script Editor does it?
```java
String script = "print(\"test\");";
scriptService.run("dummy.py", script, true);
```
That will also serve to enable support for `@` parameters, although it will only work out of the box for stuff like services—if you put a number there, the notebook has no way of harvesting it from the user since it runs headless under the hood.

The `dummy.py` is only used to decipher which script language to use when executing, based on the file extension.

**Comment by ctrueden** [comment]
It occurs to me that we do need to make sure the same `ScriptEngine` is reused between cells, of course. For reference, [here](https://github.com/scijava/script-editor/blob/script-editor-0.1.1/src/main/java/org/scijava/ui/swing/script/TextEditor.java#L2335-L2356) is how the Script Editor executes code. But I think it does not reuse the `ScriptEngine`. We will find a way to do that.

**Comment by hadim** [comment]
Thank you @ctrueden .

I end up with the same conclusion and I am now more convinced with your input.

I think the best way to tackle this is to modify the various `scripting-LANGUAGE` repo to work both with the kernel and the ScriptEditor. Because as you said, cells will have to reuse the `ScriptEngine` object to not loose all the previously executed code. I expect this to be easy to do.

Then on midterm those repos will also contain the code to handle various outputs (with different mimetypes) and autocomplete machinery. That should be a bit harder to do because it's language specific and the kernel will probably need some code refactoring.

Let me know if this strategy looks good.

**Comment by imagejan** [comment]
> Have you considered simply executing the script using the ScriptService instead, similar to how the Script Editor does it?

I implemented the same in a PR for ActionBar a while ago: https://github.com/mutterer/ActionBar/pull/3

> But I think it does not reuse the ScriptEngine. We will find a way to do that.

If we make it reuse the ScriptEngine, it would also solve the issue of re-using variable between different buttons of an Action Bar mentioned in above PR. 😄

**Comment by hadim** [comment]
Here is the code I am playing with : 

```java
public static void test1(Context context) throws ModuleException {

        ScriptService scriptService = context.getService(ScriptService.class);
        ModuleService moduleService = context.getService(ModuleService.class);

        ScriptLanguage scriptLanguage = scriptService.getLanguageByName("python");

        final Writer output = new PrintWriter(System.out);
        final Writer errors = new PrintWriter(System.out);
        final Reader reader = new StringReader("print('Hello');last=895");

        ScriptInfo info = new ScriptInfo(context, "dummy.py", reader);
        ScriptModule module = info.createModule();
        context.inject(module);

        // use the currently selected language to execute the script
        module.setLanguage(scriptLanguage);

        // map stdout and stderr to the UI
        module.setOutputWriter(output);
        module.setErrorWriter(errors);

        // execute the script
        try {
            module = moduleService.run(module, true).get();
        } catch (final InterruptedException e) {
            System.out.println("Interrupted " + e);
        } catch (final ExecutionException e) {
            System.out.println(e);
        }
        
        System.out.println(module.getOutputs());
                       
    }
```

The issue with the actual `ScriptModule` `ScriptInfo` combo, is that it's not flexible enough to allow me to reuse code. Actually, I can't even specify a new `ScriptInfo` for a given `ScriptModule` neither I can set a new `StringReader` for a given `ScriptInfo`.

I think those classes will have to be modified to allow this kind of flexibility.

**Comment by ctrueden** [comment]
Regardless of whether we move away from `eval` in this repo, the fact that it is broken in Jython is still a problem, which I have started to address here: https://github.com/scijava/scripting-jython/compare/script-engine-eval. It is now working, although I still have to fix the reference cleanup logic on that branch before merging.

In general, everyone at NEUBIAS is super excited to have ImageJ working in Jupyter, so I'll try to work more on this repo in coming weeks—although I'll be pretty busy with hackathon stuff from now through the end of February.

Will keep you posted, @hadim.

**Comment by hadim** [comment]
Hope NEUBIAS was fun !

Great to hear about Jupyter. I am also excited about this kernel.

in PR #12, I am trying to refactor a bit the way the kernel work by using `ScriptModule` from the scijava project. I have some issues making it work. I think I don't understand well enough the way input and output work in Java and so I am lost trying to redirecting various I/O stuff from the kernel to output of the kernel.

I would suggest you start with that since I think it would be really helpful to have `ScriptModule` in this kernel. It could be used as a bridge between the kernel and more language specific features such as output formatting and annotation support.

**Comment by ctrueden** [comment]
Just to follow up, the `script-engine-eval` branch is now merged to master on `scijava/scripting-jython`.

I will try to check out PR #12 here soon...

**Comment by hadim** [comment]
I have just tested and the `script-engine-eval` fixed the bug. Python code now works on the `master` branch of this repo (you should maybe make a release of `scripting-jython`).

I am gonna close here. I think we should now try to get a better integration between this kernel and the languages we want to support.

As I said all the languages specific features should live into the various `scripting-LANGUAGE-NAME` packages. 

For that, we need to design an API in `scijava-jupyter-kernel` that match features needed to get a good kernel (those things could also be reused in the ScriptEditor) such as; code completion, output formatting for images and tables, etc
